// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharedWishlistWebApp.Server.Models;

#nullable disable

namespace SharedWishlistWebApp.Server.Migrations
{
    [DbContext(typeof(WishlistApiContext))]
    partial class WishlistApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.GiftItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WishlistId");

                    b.ToTable("GiftItems");
                });

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.GiftReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ContributionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GiftItemId")
                        .HasColumnType("int");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiftItemId");

                    b.HasIndex("GuestId");

                    b.ToTable("GiftReservations");
                });

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.WishlistGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistGuests");
                });

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.GiftItem", b =>
                {
                    b.HasOne("SharedWishlistWebApp.Server.Models.Wishlist", "Wishlist")
                        .WithMany("GiftItems")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.GiftReservation", b =>
                {
                    b.HasOne("SharedWishlistWebApp.Server.Models.GiftItem", "GiftItem")
                        .WithMany("GiftReservations")
                        .HasForeignKey("GiftItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedWishlistWebApp.Server.Models.Guest", "Guest")
                        .WithMany("GiftReservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiftItem");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.WishlistGuest", b =>
                {
                    b.HasOne("SharedWishlistWebApp.Server.Models.Guest", "Guest")
                        .WithMany("WishlistGuests")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedWishlistWebApp.Server.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistGuests")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.GiftItem", b =>
                {
                    b.Navigation("GiftReservations");
                });

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.Guest", b =>
                {
                    b.Navigation("GiftReservations");

                    b.Navigation("WishlistGuests");
                });

            modelBuilder.Entity("SharedWishlistWebApp.Server.Models.Wishlist", b =>
                {
                    b.Navigation("GiftItems");

                    b.Navigation("WishlistGuests");
                });
#pragma warning restore 612, 618
        }
    }
}
